HBASE-25266 [hbase-operator-tools] Add a repair tool for moving stale…
apache/hbase-operator-tools pull request #78
Opened 2020-11-10 13:52 UTC by wchevreuil

… regions dir not present in meta away from table dir

2020-11-10 14:02 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  3s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 28s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   0m 28s |  master passed  |
| +1 :green_heart: |  compile  |   0m 16s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m  9s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 11s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  3s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m 18s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 16s |  the patch passed  |
| -1 :x: |  javac  |   0m  7s |  hbase-tools generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0)  |
| -1 :x: |  checkstyle  |   0m  4s |  hbase-hbck2: The patch generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0)  |
| -1 :x: |  checkstyle  |   0m  3s |  hbase-tools: The patch generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m  9s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   3m 57s |  hbase-hbck2 in the patch passed.  |
| -1 :x: |  unit  |   2m  3s |  hbase-tools in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m  9s |  The patch does not generate ASF License warnings.  |
|  |   |   9m 54s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hbase.TestRegionsMerger |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/1/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/78 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile xml |
| uname | Linux baa5767e25ce 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / 5cdc0e2 |
| Default Java | Oracle Corporation-1.8.0_272-b10 |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/1/artifact/yetus-precommit-check/output/diff-compile-javac-hbase-tools.txt |
| checkstyle | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/1/artifact/yetus-precommit-check/output/diff-checkstyle-hbase-hbck2.txt |
| checkstyle | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/1/artifact/yetus-precommit-check/output/diff-checkstyle-hbase-tools.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/1/artifact/yetus-precommit-check/output/patch-unit-hbase-tools.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/1/testReport/ |
| Max. process+thread count | 942 (vs. ulimit of 1000) |
| modules | C: hbase-hbck2 hbase-tools U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/1/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2020-11-10 14:34 UTC, busbey commented
please update the README to explain this tool, when one should use it, how to use it, how to tell that it was successful or that it had a problem.

2020-11-10 14:48 UTC, busbey requested changes

2020-11-10 14:48 UTC, busbey commented on hbase-tools/src/main/java/org/apache/hbase/MissingRegionDirsRepairTool.java
> +      Admin admin = conn.getAdmin();
gotta close Admin instance

2020-11-10 14:48 UTC, busbey commented on hbase-tools/src/main/java/org/apache/hbase/MissingRegionDirsRepairTool.java
> +    Path runPath = new Path(HBCKFsUtils.getRootDir(conf),
this should be in some common dir under the root dir so we don't get a bunch of directories in the hbase root dir. that directory should start with a `.` like the hbck repair directory.

2020-11-10 14:48 UTC, busbey commented on hbase-tools/src/main/java/org/apache/hbase/MissingRegionDirsRepairTool.java
> +                HBCKFsUtils.copyFilesParallel(fs, region, fs, sidelinedRegionDir, conf, 3);
what happens if we run this tool multiple times in parallel?

2020-11-10 14:48 UTC, busbey commented on hbase-tools/pom.xml
> +            <artifactId>hbase-hbck2</artifactId>
why have this as a standalone tool rather than as a command under hbck2?

2020-11-10 14:48 UTC, busbey commented on hbase-tools/src/main/java/org/apache/hbase/MissingRegionDirsRepairTool.java
> +    this.hbck = new HBCK2(conf);
this use of the hbck2 object makes me think this should be an hbck2 command.

2020-11-10 16:28 UTC, wchevreuil commented on hbase-tools/pom.xml
> +            <artifactId>hbase-hbck2</artifactId>
My view is that it does much more stuffs than a single hbck2 command should do. And it does not directly perform any sort of changes on meta, nor relies on Hbck interfaces for modifications of meta state. It does reuse a reporting (readonly) HBCK2 method, plus some of the FS utilities currently implemented on HBCKFsUtils, but that's just for reuse.

2020-11-10 16:28 UTC, wchevreuil commented on hbase-tools/src/main/java/org/apache/hbase/MissingRegionDirsRepairTool.java
> +    this.hbck = new HBCK2(conf);
See previous comment.

2020-11-10 19:34 UTC, wchevreuil commented on hbase-tools/src/main/java/org/apache/hbase/MissingRegionDirsRepairTool.java
> +                HBCKFsUtils.copyFilesParallel(fs, region, fs, sidelinedRegionDir, conf, 3);
For this copyFilesParallel method call, there wouldn't be any problems, as the sidelinedRegionDir is under the individual "missing_dirs_repair_TS" dir. But if each run gets here at different times, later runs would not find already sidelined regions. There's still possibility that same region gets sidelined by different runs, which would also bulkload the regions files again. Not ideal in terms of resources usage, but still fine for data consistency sake. I guess we can implement some sort of lock file in a given hdfs location to avoid multiple runs?

2020-11-10 19:51 UTC, wchevreuil commented
> please update the README to explain this tool, when one should use it, how to use it, how to tell that it was successful or that it had a problem.

Thansk, @busbey , will do it on a next commit tomorrow. Had pushed new commit today addressing checkstyles and some other comments.

2020-11-10 20:00 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 43s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 25s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   0m 27s |  master passed  |
| +1 :green_heart: |  compile  |   0m 16s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m 10s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 11s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  3s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m 18s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 17s |  the patch passed  |
| -1 :x: |  javac  |   0m  8s |  hbase-tools generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0)  |
| +1 :green_heart: |  checkstyle  |   0m  7s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 10s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   5m 44s |  hbase-hbck2 in the patch passed.  |
| -1 :x: |  unit  |   2m  1s |  hbase-tools in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m  9s |  The patch does not generate ASF License warnings.  |
|  |   |  11m 14s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hbase.TestRegionsMerger |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/2/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/78 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile xml |
| uname | Linux 777b3951a706 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / 5cdc0e2 |
| Default Java | Oracle Corporation-1.8.0_272-b10 |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/2/artifact/yetus-precommit-check/output/diff-compile-javac-hbase-tools.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/2/artifact/yetus-precommit-check/output/patch-unit-hbase-tools.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/2/testReport/ |
| Max. process+thread count | 942 (vs. ulimit of 1000) |
| modules | C: hbase-hbck2 hbase-tools U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/2/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2020-11-12 10:08 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  1s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 28s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   0m 27s |  master passed  |
| +1 :green_heart: |  compile  |   0m 17s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m 10s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 13s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  3s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m 20s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 17s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 17s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m  8s |  the patch passed  |
| -1 :x: |  whitespace  |   0m  0s |  The patch has 12 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m  9s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   3m 58s |  hbase-hbck2 in the patch passed.  |
| -1 :x: |  unit  |   1m 22s |  hbase-tools in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m  9s |  The patch does not generate ASF License warnings.  |
|  |   |   9m 15s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hbase.TestRegionsMerger |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/3/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/78 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile markdownlint xml |
| uname | Linux 45fe78d1b938 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / 5cdc0e2 |
| Default Java | Oracle Corporation-1.8.0_275-b01 |
| whitespace | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/3/artifact/yetus-precommit-check/output/whitespace-eol.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/3/artifact/yetus-precommit-check/output/patch-unit-hbase-tools.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/3/testReport/ |
| Max. process+thread count | 941 (vs. ulimit of 1000) |
| modules | C: hbase-hbck2 hbase-tools U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/3/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-01-15 19:00 UTC, busbey commented on hbase-tools/src/main/java/org/apache/hbase/MissingRegionDirsRepairTool.java
> +                HBCKFsUtils.copyFilesParallel(fs, region, fs, sidelinedRegionDir, conf, 3);
> I guess we can implement some sort of lock file in a given hdfs location to avoid multiple runs?

yeah. I think fine to do as a follow on though since it doesn't impact correctness?

2021-01-15 19:03 UTC, busbey approved these changes
needs a rebase and to make sure qabot is clean. besides those, lgtm

2021-01-18 11:04 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 14s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 30s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   0m 28s |  master passed  |
| +1 :green_heart: |  compile  |   0m 16s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m  9s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 12s |  master passed  |
| -0 :warning: |  patch  |   0m 28s |  Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  3s |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |   0m  7s |  hbase-hbck2 in the patch failed.  |
| -1 :x: |  mvninstall  |   0m  8s |  hbase-tools in the patch failed.  |
| -1 :x: |  compile  |   0m  7s |  hbase-hbck2 in the patch failed.  |
| -1 :x: |  compile  |   0m  7s |  hbase-tools in the patch failed.  |
| -1 :x: |  javac  |   0m  7s |  hbase-hbck2 in the patch failed.  |
| -1 :x: |  javac  |   0m  7s |  hbase-tools in the patch failed.  |
| -1 :x: |  checkstyle  |   0m  5s |  hbase-hbck2: The patch generated 5 new + 0 unchanged - 0 fixed = 5 total (was 0)  |
| -1 :x: |  whitespace  |   0m  0s |  The patch has 12 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m  9s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   0m  8s |  hbase-hbck2 in the patch failed.  |
| -1 :x: |  unit  |   0m  7s |  hbase-tools in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m  9s |  The patch does not generate ASF License warnings.  |
|  |   |   4m 16s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/4/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/78 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile markdownlint xml |
| uname | Linux b3b4cc1efc2f 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / b461d58 |
| Default Java | Oracle Corporation-1.8.0_275-b01 |
| mvninstall | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/4/artifact/yetus-precommit-check/output/patch-mvninstall-hbase-hbck2.txt |
| mvninstall | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/4/artifact/yetus-precommit-check/output/patch-mvninstall-hbase-tools.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/4/artifact/yetus-precommit-check/output/patch-compile-hbase-hbck2.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/4/artifact/yetus-precommit-check/output/patch-compile-hbase-tools.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/4/artifact/yetus-precommit-check/output/patch-compile-hbase-hbck2.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/4/artifact/yetus-precommit-check/output/patch-compile-hbase-tools.txt |
| checkstyle | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/4/artifact/yetus-precommit-check/output/diff-checkstyle-hbase-hbck2.txt |
| whitespace | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/4/artifact/yetus-precommit-check/output/whitespace-eol.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/4/artifact/yetus-precommit-check/output/patch-unit-hbase-hbck2.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/4/artifact/yetus-precommit-check/output/patch-unit-hbase-tools.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/4/testReport/ |
| Max. process+thread count | 35 (vs. ulimit of 1000) |
| modules | C: hbase-hbck2 hbase-tools U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/4/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-01-18 12:11 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 40s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 24s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   0m 25s |  master passed  |
| +1 :green_heart: |  compile  |   0m 16s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m 10s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 11s |  master passed  |
| -0 :warning: |  patch  |   0m 28s |  Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  3s |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |   0m  7s |  hbase-hbck2 in the patch failed.  |
| -1 :x: |  mvninstall  |   0m  7s |  hbase-tools in the patch failed.  |
| -1 :x: |  compile  |   0m  7s |  hbase-hbck2 in the patch failed.  |
| -1 :x: |  compile  |   0m  7s |  hbase-tools in the patch failed.  |
| -1 :x: |  javac  |   0m  7s |  hbase-hbck2 in the patch failed.  |
| -1 :x: |  javac  |   0m  7s |  hbase-tools in the patch failed.  |
| -1 :x: |  checkstyle  |   0m  3s |  hbase-hbck2: The patch generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0)  |
| -1 :x: |  whitespace  |   0m  0s |  The patch has 13 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| +1 :green_heart: |  xml  |   0m  0s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m  9s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   0m  8s |  hbase-hbck2 in the patch failed.  |
| -1 :x: |  unit  |   0m  7s |  hbase-tools in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m  9s |  The patch does not generate ASF License warnings.  |
|  |   |   3m 32s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/6/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/78 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile markdownlint xml |
| uname | Linux a299d65dcde0 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / b461d58 |
| Default Java | Oracle Corporation-1.8.0_275-b01 |
| mvninstall | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/6/artifact/yetus-precommit-check/output/patch-mvninstall-hbase-hbck2.txt |
| mvninstall | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/6/artifact/yetus-precommit-check/output/patch-mvninstall-hbase-tools.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/6/artifact/yetus-precommit-check/output/patch-compile-hbase-hbck2.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/6/artifact/yetus-precommit-check/output/patch-compile-hbase-tools.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/6/artifact/yetus-precommit-check/output/patch-compile-hbase-hbck2.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/6/artifact/yetus-precommit-check/output/patch-compile-hbase-tools.txt |
| checkstyle | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/6/artifact/yetus-precommit-check/output/diff-checkstyle-hbase-hbck2.txt |
| whitespace | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/6/artifact/yetus-precommit-check/output/whitespace-eol.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/6/artifact/yetus-precommit-check/output/patch-unit-hbase-hbck2.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/6/artifact/yetus-precommit-check/output/patch-unit-hbase-tools.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/6/testReport/ |
| Max. process+thread count | 35 (vs. ulimit of 1000) |
| modules | C: hbase-hbck2 hbase-tools U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/6/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-01-18 14:21 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 41s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 25s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   0m 27s |  master passed  |
| +1 :green_heart: |  compile  |   0m 16s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m  9s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 11s |  master passed  |
| -0 :warning: |  patch  |   0m 27s |  Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  2s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m 19s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 16s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 16s |  the patch passed  |
| -1 :x: |  checkstyle  |   0m  4s |  hbase-hbck2: The patch generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0)  |
| -1 :x: |  whitespace  |   0m  0s |  The patch has 13 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| +1 :green_heart: |  xml  |   0m  0s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 10s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   6m 41s |  hbase-hbck2 in the patch passed.  |
| -1 :x: |  unit  |   1m 22s |  hbase-tools in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 10s |  The patch does not generate ASF License warnings.  |
|  |   |  11m 30s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hbase.TestRegionsMerger |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/8/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/78 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile markdownlint xml |
| uname | Linux b331f65bbfa3 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / b461d58 |
| Default Java | Oracle Corporation-1.8.0_275-b01 |
| checkstyle | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/8/artifact/yetus-precommit-check/output/diff-checkstyle-hbase-hbck2.txt |
| whitespace | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/8/artifact/yetus-precommit-check/output/whitespace-eol.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/8/artifact/yetus-precommit-check/output/patch-unit-hbase-tools.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/8/testReport/ |
| Max. process+thread count | 931 (vs. ulimit of 1000) |
| modules | C: hbase-hbck2 hbase-tools U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/8/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-01-19 11:17 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 43s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   1m  7s |  Maven dependency ordering for branch  |
| -1 :x: |  mvninstall  |   0m 20s |  root in master failed.  |
| +1 :green_heart: |  compile  |   0m 17s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m  9s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 11s |  master passed  |
| -0 :warning: |  patch  |   0m 27s |  Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  3s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m 20s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 16s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 16s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m  7s |  the patch passed  |
| -1 :x: |  whitespace  |   0m  0s |  The patch has 1 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| +1 :green_heart: |  xml  |   0m  0s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 10s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   6m 40s |  hbase-hbck2 in the patch passed.  |
| -1 :x: |  unit  |   2m  0s |  hbase-tools in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m  9s |  The patch does not generate ASF License warnings.  |
|  |   |  12m 45s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hbase.TestRegionsMerger |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/9/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/78 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile markdownlint xml |
| uname | Linux 986dbf5fd72d 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / b461d58 |
| Default Java | Oracle Corporation-1.8.0_275-b01 |
| mvninstall | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/9/artifact/yetus-precommit-check/output/branch-mvninstall-root.txt |
| whitespace | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/9/artifact/yetus-precommit-check/output/whitespace-eol.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/9/artifact/yetus-precommit-check/output/patch-unit-hbase-tools.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/9/testReport/ |
| Max. process+thread count | 940 (vs. ulimit of 1000) |
| modules | C: hbase-hbck2 hbase-tools U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/9/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-01-19 13:14 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 43s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 27s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   0m 24s |  master passed  |
| +1 :green_heart: |  compile  |   0m 27s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m 13s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 16s |  master passed  |
| -0 :warning: |  patch  |   0m 40s |  Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  4s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m 36s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 26s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 26s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 10s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 15s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   6m  9s |  hbase-hbck2 in the patch passed.  |
| -1 :x: |  unit  |   1m 21s |  hbase-tools in the patch failed.  |
| -1 :x: |  unit  |  18m 44s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 13s |  The patch does not generate ASF License warnings.  |
|  |   |  30m 49s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hbase.TestRegionsMerger |
|   | hbase.TestRegionsMerger |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/10/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/78 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile markdownlint xml |
| uname | Linux 3c5cbb5e4184 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / b461d58 |
| Default Java | Oracle Corporation-1.8.0_275-b01 |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/10/artifact/yetus-precommit-check/output/patch-unit-hbase-tools.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/10/artifact/yetus-precommit-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/10/testReport/ |
| Max. process+thread count | 942 (vs. ulimit of 1000) |
| modules | C: hbase-hbck2 hbase-tools . U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/10/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-01-19 15:17 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 43s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 29s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   0m 25s |  master passed  |
| +1 :green_heart: |  compile  |   0m 26s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m 13s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 16s |  master passed  |
| -0 :warning: |  patch  |   0m 40s |  Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  4s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m 35s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 26s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 26s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 11s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 15s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   6m 38s |  hbase-hbck2 in the patch passed.  |
| -1 :x: |  unit  |   1m 20s |  hbase-tools in the patch failed.  |
| -1 :x: |  unit  |  42m 46s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 13s |  The patch does not generate ASF License warnings.  |
|  |   |  55m 22s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hbase.TestRegionsMerger |
|   | hbase.TestRegionsMerger |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/11/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/78 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile markdownlint xml |
| uname | Linux 63dcccb810a5 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / b461d58 |
| Default Java | Oracle Corporation-1.8.0_275-b01 |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/11/artifact/yetus-precommit-check/output/patch-unit-hbase-tools.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/11/artifact/yetus-precommit-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/11/testReport/ |
| Max. process+thread count | 942 (vs. ulimit of 1000) |
| modules | C: hbase-hbck2 hbase-tools . U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/11/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-01-22 17:57 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 42s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 2 new or modified test files.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 30s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   0m 27s |  master passed  |
| +1 :green_heart: |  compile  |   0m 27s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m 13s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 17s |  master passed  |
| -0 :warning: |  patch  |   0m 40s |  Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  4s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m 35s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 27s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 27s |  the patch passed  |
| -1 :x: |  checkstyle  |   0m  4s |  hbase-tools: The patch generated 1 new + 4 unchanged - 1 fixed = 5 total (was 5)  |
| -1 :x: |  checkstyle  |   0m  3s |  root: The patch generated 1 new + 4 unchanged - 1 fixed = 5 total (was 5)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 15s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   6m 10s |  hbase-hbck2 in the patch passed.  |
| -1 :x: |  unit  |   2m 15s |  hbase-tools in the patch failed.  |
| -1 :x: |  unit  |   6m  1s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 13s |  The patch does not generate ASF License warnings.  |
|  |   |  19m  5s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hbase.TestHBCK2 |
|   | hbase.TestRegionsMerger |
|   | hbase.TestRegionsMerger |
|   | hbase.TestHBCK2 |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/20/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/78 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile markdownlint xml |
| uname | Linux f66292290f28 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / b461d58 |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
| checkstyle | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/20/artifact/yetus-precommit-check/output/diff-checkstyle-hbase-tools.txt |
| checkstyle | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/20/artifact/yetus-precommit-check/output/diff-checkstyle-root.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/20/artifact/yetus-precommit-check/output/patch-unit-hbase-hbck2.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/20/artifact/yetus-precommit-check/output/patch-unit-hbase-tools.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/20/artifact/yetus-precommit-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/20/testReport/ |
| Max. process+thread count | 938 (vs. ulimit of 1000) |
| modules | C: hbase-hbck2 hbase-tools . U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/20/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-01-22 19:22 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 44s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 2 new or modified test files.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 29s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   0m 28s |  master passed  |
| +1 :green_heart: |  compile  |   0m 27s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m 14s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 17s |  master passed  |
| -0 :warning: |  patch  |   0m 41s |  Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  4s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m 35s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 27s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 27s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m  4s |  The patch passed checkstyle in hbase-hbck2  |
| +1 :green_heart: |  checkstyle  |   0m  3s |  hbase-tools: The patch generated 0 new + 4 unchanged - 1 fixed = 4 total (was 5)  |
| +1 :green_heart: |  checkstyle  |   0m  4s |  root: The patch generated 0 new + 4 unchanged - 1 fixed = 4 total (was 5)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 15s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   6m 33s |  hbase-hbck2 in the patch failed.  |
| +1 :green_heart: |  unit  |   2m 55s |  hbase-tools in the patch passed.  |
| +1 :green_heart: |  unit  |  21m 26s |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 14s |  The patch does not generate ASF License warnings.  |
|  |   |  35m 37s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/22/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/78 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile markdownlint xml |
| uname | Linux 5b1c80e1180b 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / b461d58 |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/22/artifact/yetus-precommit-check/output/patch-unit-hbase-hbck2.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/22/testReport/ |
| Max. process+thread count | 941 (vs. ulimit of 1000) |
| modules | C: hbase-hbck2 hbase-tools . U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/22/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-01-25 10:22 UTC, Apache-HBase commented
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 38s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 2 new or modified test files.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 30s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   0m 25s |  master passed  |
| +1 :green_heart: |  compile  |   0m 27s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m 13s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 16s |  master passed  |
| -0 :warning: |  patch  |   0m 40s |  Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  4s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m 36s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 26s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 26s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m  4s |  The patch passed checkstyle in hbase-hbck2  |
| +1 :green_heart: |  checkstyle  |   0m  3s |  hbase-tools: The patch generated 0 new + 4 unchanged - 1 fixed = 4 total (was 5)  |
| +1 :green_heart: |  checkstyle  |   0m  4s |  root: The patch generated 0 new + 4 unchanged - 1 fixed = 4 total (was 5)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 16s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   6m 34s |  hbase-hbck2 in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 57s |  hbase-tools in the patch passed.  |
| +1 :green_heart: |  unit  |   9m 33s |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 13s |  The patch does not generate ASF License warnings.  |
|  |   |  23m 35s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/23/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/78 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile spotbugs findbugs checkstyle markdownlint |
| uname | Linux f1ec3f5f423b 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / b461d58 |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/23/testReport/ |
| Max. process+thread count | 923 (vs. ulimit of 1000) |
| modules | C: hbase-hbck2 hbase-tools . U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/23/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-01-25 11:54 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  7s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 27s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   0m 24s |  master passed  |
| +1 :green_heart: |  compile  |   0m 26s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m 13s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 18s |  master passed  |
| -0 :warning: |  patch  |   0m 41s |  Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  4s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m 36s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 26s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 26s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 11s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 15s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   6m 37s |  hbase-hbck2 in the patch passed.  |
| -1 :x: |  unit  |   1m 21s |  hbase-tools in the patch failed.  |
| -1 :x: |  unit  |   7m 27s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 13s |  The patch does not generate ASF License warnings.  |
|  |   |  20m 23s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hbase.TestRegionsMerger |
|   | hbase.TestRegionsMerger |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/24/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/78 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile markdownlint xml |
| uname | Linux 2ba89051d596 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / b461d58 |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/24/artifact/yetus-precommit-check/output/patch-unit-hbase-tools.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/24/artifact/yetus-precommit-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/24/testReport/ |
| Max. process+thread count | 941 (vs. ulimit of 1000) |
| modules | C: hbase-hbck2 hbase-tools . U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/24/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-01-25 12:18 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 37s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 24s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   0m 25s |  master passed  |
| +1 :green_heart: |  compile  |   0m 16s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m  9s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 11s |  master passed  |
| -0 :warning: |  patch  |   0m 27s |  Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  3s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m 19s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 16s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 16s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m  7s |  the patch passed  |
| -1 :x: |  whitespace  |   0m  0s |  The patch has 1 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 10s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   6m 40s |  hbase-hbck2 in the patch passed.  |
| -1 :x: |  unit  |   2m  0s |  hbase-tools in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m  9s |  The patch does not generate ASF License warnings.  |
|  |   |  12m  2s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hbase.TestRegionsMerger |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/25/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/78 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile markdownlint xml |
| uname | Linux 8e9495c0ccd1 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / b461d58 |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
| whitespace | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/25/artifact/yetus-precommit-check/output/whitespace-eol.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/25/artifact/yetus-precommit-check/output/patch-unit-hbase-tools.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/25/testReport/ |
| Max. process+thread count | 942 (vs. ulimit of 1000) |
| modules | C: hbase-hbck2 hbase-tools U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/25/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-01-25 14:54 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 44s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 28s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   0m 27s |  master passed  |
| +1 :green_heart: |  compile  |   0m 17s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m  9s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 11s |  master passed  |
| -0 :warning: |  patch  |   0m 28s |  Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  3s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m 19s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 17s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 17s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m  7s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  0s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 10s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   6m 46s |  hbase-hbck2 in the patch passed.  |
| -1 :x: |  unit  |   2m  1s |  hbase-tools in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m  9s |  The patch does not generate ASF License warnings.  |
|  |   |  12m 22s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hbase.TestRegionsMerger |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/26/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/78 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile markdownlint xml |
| uname | Linux fe69d793106a 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / b461d58 |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/26/artifact/yetus-precommit-check/output/patch-unit-hbase-tools.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/26/testReport/ |
| Max. process+thread count | 942 (vs. ulimit of 1000) |
| modules | C: hbase-hbck2 hbase-tools U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-78/26/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-01-25 18:13 UTC, wchevreuil commented
I had reverted the changes to fix UT flakeyness after @busbey approval because those were unrelated to this PR. I'm going to merge this now and open a new one for the UTs flakeyness, as it may involve some changes on files not relevant to this PR.

2021-01-25 18:14 UTC, merged