HBASE-25874 [hbase-operator-tools]Add tool for identifying 'unknown s…
apache/hbase-operator-tools pull request #86
Opened 2021-05-10 10:54 UTC by wchevreuil

…ervers' from master logs, then submit SCPs for each of those.

2021-05-10 11:00 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 26s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   1m  9s |  master passed  |
| +1 :green_heart: |  compile  |   0m  8s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m  5s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m  6s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m  8s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m  8s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m  8s |  the patch passed  |
| -1 :x: |  checkstyle  |   0m  3s |  hbase-tools: The patch generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0)  |
| -1 :x: |  whitespace  |   0m  0s |  The patch has 4 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| +1 :green_heart: |  javadoc  |   0m  5s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m  4s |  hbase-tools in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m  5s |  The patch does not generate ASF License warnings.  |
|  |   |   5m 34s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-86/1/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/86 |
| Optional Tests | dupname asflicense markdownlint javac javadoc unit spotbugs findbugs checkstyle compile |
| uname | Linux a435d7ca80ab 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / f118dfb |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
| checkstyle | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-86/1/artifact/yetus-precommit-check/output/diff-checkstyle-hbase-tools.txt |
| whitespace | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-86/1/artifact/yetus-precommit-check/output/whitespace-eol.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-86/1/testReport/ |
| Max. process+thread count | 1223 (vs. ulimit of 5000) |
| modules | C: hbase-tools U: hbase-tools |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-86/1/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-05-10 16:08 UTC, joshelser requested changes
I think my main worry is about relying on log file parsing for this. That's not to say this is flawed -- it just is what it is.

Is there a reason you went for this approach rather than trying to read meta and interrogate the Master as to who the active RegionServers are?

2021-05-10 19:20 UTC, wchevreuil commented
> I think my main worry is about relying on log file parsing for this. That's not to say this is flawed -- it just is what it is.

Yeah, it's fragile indeed, but we are targeting this mainly for the unfortunate souls running hbase versions lower than 2.2.7, 2.3.5 and 2.4.7, as mentioned on the readme, so there shouldn't be any changes on logging format for these already released versions. For any version from the above mentioned onwards, there's already hbck2 recoverUnknown method.

> Is there a reason you went for this approach rather than trying to read meta and interrogate the Master as to who the active RegionServers are?

Although meta is already online, master has not completed initialisation (because of namespace table region stuck on a unknown server), so it pushes back any client requests.

2021-05-10 19:25 UTC, joshelser commented
> Although meta is already online, master has not completed initialisation (because of namespace table region stuck on a unknown server), so it pushes back any client requests.

Argh. The gift that keeps on giving.

2021-05-10 19:27 UTC, wchevreuil commented on hbase-tools/src/main/java/org/apache/hbase/RegionsOnUnknownServersRecoverer.java
> +      reader = new BufferedReader(new FileReader(new File(args[0])));
It's actually closed by `reader.close`, as it's the IS wrapped in there, no?

2021-05-10 19:35 UTC, joshelser commented on hbase-tools/src/main/java/org/apache/hbase/RegionsOnUnknownServersRecoverer.java
> +      reader = new BufferedReader(new FileReader(new File(args[0])));
Oh, yes, you're right. I missed it down there.

2021-05-11 09:04 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 43s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 53s |  master passed  |
| +1 :green_heart: |  compile  |   0m  8s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m  6s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m  7s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m  9s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m  8s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m  8s |  the patch passed  |
| -1 :x: |  checkstyle  |   0m  4s |  hbase-tools: The patch generated 2 new + 0 unchanged - 0 fixed = 2 total (was 0)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m  5s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   2m 17s |  hbase-tools in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m  6s |  The patch does not generate ASF License warnings.  |
|  |   |   4m 54s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hbase.TestRegionsMerger |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-86/2/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/86 |
| Optional Tests | dupname asflicense markdownlint javac javadoc unit spotbugs findbugs checkstyle compile |
| uname | Linux b9155d65bc12 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / f118dfb |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
| checkstyle | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-86/2/artifact/yetus-precommit-check/output/diff-checkstyle-hbase-tools.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-86/2/artifact/yetus-precommit-check/output/patch-unit-hbase-tools.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-86/2/testReport/ |
| Max. process+thread count | 1169 (vs. ulimit of 5000) |
| modules | C: hbase-tools U: hbase-tools |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-86/2/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-05-12 10:56 UTC, petersomogyi reviewed
Looks fine overall. Some nits.

2021-05-12 10:56 UTC, petersomogyi commented on hbase-tools/src/main/java/org/apache/hbase/RegionsOnUnknownServersRecoverer.java
> +        + "Arguments are: <PATH_TO_MASTER_LOGS> [dryRun]");
From the usage message it is not obvious that the `[dryRun]` parameter should be `true`.

2021-05-12 10:56 UTC, petersomogyi commented on hbase-tools/README.md
> +$ hbase org.apache.hbase.RegionsOnUnknownServersRecoverer PATH_TO_MASTER_LOGS
The dry-run option is not mentioned here.

2021-05-12 12:01 UTC, wchevreuil commented on hbase-tools/src/main/java/org/apache/hbase/RegionsOnUnknownServersRecoverer.java
> +        + "Arguments are: <PATH_TO_MASTER_LOGS> [dryRun]");
Just wanted to mention the available options here. I guess we can explain the `dryRun` option in the README only?

2021-05-12 12:11 UTC, Apache-HBase commented
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 43s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 57s |  master passed  |
| +1 :green_heart: |  compile  |   0m  8s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m  6s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m  7s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 11s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m  8s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m  8s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m  4s |  the patch passed  |
| -1 :x: |  whitespace  |   0m  0s |  The patch has 1 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| +1 :green_heart: |  javadoc  |   0m  5s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 13s |  hbase-tools in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m  6s |  The patch does not generate ASF License warnings.  |
|  |   |   4m 55s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-86/4/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/86 |
| Optional Tests | dupname asflicense markdownlint javac javadoc unit spotbugs findbugs checkstyle compile |
| uname | Linux 814902db5e44 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / f118dfb |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
| whitespace | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-86/4/artifact/yetus-precommit-check/output/whitespace-eol.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-86/4/testReport/ |
| Max. process+thread count | 1214 (vs. ulimit of 5000) |
| modules | C: hbase-tools U: hbase-tools |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-86/4/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-05-12 13:26 UTC, petersomogyi commented on hbase-tools/src/main/java/org/apache/hbase/RegionsOnUnknownServersRecoverer.java
> +        + "Arguments are: <PATH_TO_MASTER_LOGS> [dryRun]");
Having it in the readme is enough but in my opinion, it is still not clear what an operator should use as the second parameter.

hbase org.apache.hbase.RegionsOnUnknownServersRecoverer /var/log/hbase.log true
hbase org.apache.hbase.RegionsOnUnknownServersRecoverer /var/log/hbase.log dryRun

Anything passed that is not `true` will schedule SCPs because the default option is dryrun=false.

2021-05-12 13:48 UTC, Apache-HBase commented
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 50s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 53s |  master passed  |
| +1 :green_heart: |  compile  |   0m  9s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m  6s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m  7s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m  9s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m  9s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m  9s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m  3s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m  5s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 22s |  hbase-tools in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m  6s |  The patch does not generate ASF License warnings.  |
|  |   |   6m  8s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-86/5/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/86 |
| Optional Tests | dupname asflicense markdownlint javac javadoc unit spotbugs findbugs checkstyle compile |
| uname | Linux 590978ef2ef2 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / f118dfb |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-86/5/testReport/ |
| Max. process+thread count | 1164 (vs. ulimit of 5000) |
| modules | C: hbase-tools U: hbase-tools |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-86/5/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-05-12 14:37 UTC, petersomogyi approved these changes

2021-05-12 14:40 UTC, Apache-HBase commented
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 41s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  markdownlint  |   0m  0s |  markdownlint was not available.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 49s |  master passed  |
| +1 :green_heart: |  compile  |   0m  8s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m  5s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m  7s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m  9s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m  8s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m  8s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m  3s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m  5s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 14s |  hbase-tools in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m  5s |  The patch does not generate ASF License warnings.  |
|  |   |   4m 40s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-86/6/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-operator-tools/pull/86 |
| Optional Tests | dupname asflicense markdownlint javac javadoc unit spotbugs findbugs checkstyle compile |
| uname | Linux aadddaaf6640 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / f118dfb |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-86/6/testReport/ |
| Max. process+thread count | 1210 (vs. ulimit of 5000) |
| modules | C: hbase-tools U: hbase-tools |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Operator-Tools-PreCommit/job/PR-86/6/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

2021-05-14 09:06 UTC, merged

2021-05-14 18:48 UTC, joshelser commented
Belated +1 from me. Thanks for the dryRun option, Wellington.